version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - source: code/index.html
      destination: /index.html
    - source: code/favicon.ico
      destination: /favicon.ico
    - source: code/2017MichaelRyanConsultantAWS.pdf
      destination: /2017MichaelRyanConsultantAWS.pdf
    - source: styles/*
      destination: styles/*
    - source: images/*
      destination: images/*
