version: 0.1

phases:
  install:
    commands:
      - echo Build started on `date`
#  pre_build:
#      - echo Nothing to do
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    # The files in the code directory need to be placed in the base install directory
    - index.html
    - favicon.ico
    - 2017MichaelRyanConsultantAWS.pdf
    - styles/main.css
    - images/*
  base-directory: 'code'
