version: 0.1

phases:
  install:
    commands:
      - echo Build started on `date`
#  pre_build:
#      - echo Nothing to do
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - echo Post Build commands go here
artifacts:
  files:
    # The files in the code directory need to be placed in the base install directory
    - code/index.html
    - code/favicon.ico
    - code/2017MichaelRyanConsultantAWS.pdf
    - code/styles/main.css
    - code/images/*
    base-directory: 'code'
