version: 0.1

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - cd code && npm install
      - cd code && npm test
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - cd code && npm run webpack --display-error-details
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    # The files in the code directory need to be placed in the base install directory
    - index.html
    - favicon.ico
    - 2017MichaelRyanConsultantAWS.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
  base-directory: 'code'
